In [12]:
import pandas as pd

from pathlib import Path

In [13]:
silver_path = Path("../data/silver/bank_marketing_silver.csv")

df = pd.read_csv(silver_path, sep=";")

print(f"Dados carregados: {df.shape[0]} linhas e {df.shape[1]} colunas")
df.head()

Dados carregados: 41176 linhas e 21 colunas

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic 4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin,married,basic 6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [21]:
if "duration" in df.columns:
    df = df.drop(columns=["duration"])
    print("Coluna 'duration' removida.")
else:
    print("A coluna 'duration' não existe no DataFrame.")

if "default" in df.columns:
    df = df.drop(columns=["default"])
    print("Coluna 'default' removida.")
else:
    print("A coluna 'default' não existe no DataFrame.")

A coluna 'duration' não existe no DataFrame.
Coluna 'default' removida.

In [15]:
df["never_contacted"] = (df["pdays"] == 999).astype(int)

In [17]:
df["campaign_bucket"] = pd.cut(
    df["campaign"],
    bins=[0, 1, 3, float("inf")],
    labels=["first_contact", "few_contacts", "many_contacts"]
)

In [19]:
df["previous_success"] = (
    df["poutcome"] == "success"
).astype(int)

In [20]:
df.value_counts("previous_success")

previous_success
0    39803
1     1373
Name: count, dtype: int64

In [22]:
df.head()

,age,job,marital,education,housing,loan,contact,month,day_of_week,campaign,...,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,never_contacted,campaign_bucket,previous_success
0,56,housemaid,married,basic 4y,no,no,telephone,may,mon,1,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,1,first_contact,0
1,57,services,married,high school,no,no,telephone,may,mon,1,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,1,first_contact,0
2,37,services,married,high school,yes,no,telephone,may,mon,1,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,1,first_contact,0
3,40,admin,married,basic 6y,no,no,telephone,may,mon,1,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,1,first_contact,0
4,56,services,married,high school,no,yes,telephone,may,mon,1,...,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,1,first_contact,0